services:
  clinica-nextjs:
    container_name: clinica-nextjs
    build: ./clinica-nextjs
    ports:
      - "3000:3000"
    env_file:
      - /clinica-nextjs/.env.local
    networks:
      - app-network
  clinica-chat:
    container_name: clinica-chat
    build:
      context: ./clinica-chat-api
    ports:
      - "8080:8080"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
