import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { esES } from "@clerk/localizations";
import "./globals.css";
import FloatingChat from "@/components/Chat";
import SupportChat from "@/components/ChatSoporte";
import { checkRole } from "@/utils/roles"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function  RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      variables: {
        colorPrimary: 'var(--primary)',
        colorBackground: 'var(--card)',
        colorInputBackground: 'var(--card-secondary)',
        colorNeutral: 'var(--foreground)',
        colorText: 'var(--text-primary)',
        colorInputText:  'var(--foreground)',
        colorTextOnPrimaryBackground: 'var(--primary-foreground)',
        colorShimmer: 'var(--text-primary-foreground)'
        
      }
    }
    }
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      localization={esES}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          {children}
          {(await checkRole("admin")) ? (
                <SupportChat/>
          ) : (
            <FloatingChat/>
          )}
          
          
          
        
          
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
