services:
  postgres:
    image: postgres:15-alpine
    container_name: clinica-postgres
    environment:
      POSTGRES_DB: salena_fisio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/docker-init-mejorado.sql:/docker-entrypoint-initdb.d/docker-init-mejorado.sql
    restart: unless-stopped


volumes:
  postgres_data:
