name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clinica-nextjs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Copy .env.example files
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

  build-chat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Building chat
        run: make build-chat
